kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "pwa_nginx.fullname" . }}-gomplate-datasources
  labels:
    {{- include "pwa_nginx.labels" . | nindent 4 }}
data:
  {{- if .Values.pwa_nginx.multiChannel }}
  multi-channel.yaml: {{- .Values.pwa_nginx.multiChannel | toYaml | indent 4}}
  {{- else }}
  multi-channel.yaml: |-
    .+:
      channel: default
  {{- end -}}
  {{- if .Values.pwa_nginx.cacheIgnoreParams }}
  caching-ignore-params.yaml: {{- .Values.pwa_nginx.cacheIgnoreParams | toYaml | indent 4}}
  {{- else }}
  caching-ignore-params.yaml: |-
    params: []
  {{- end -}}