apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intershop-pwa.fullname" . }}
  labels:
  {{- include "intershop-pwa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pwa_ssr.replicaCount }}
  selector:
    matchLabels:
      {{- include "intershop-pwa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pwa_ssr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "intershop-pwa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.pwa_ssr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.pwa_ssr.image.repository }}:{{ .Values.pwa_ssr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pwa_ssr.image.pullPolicy }}
          env:
          - name: ICM_BASE_URL
            value: "{{ .Values.pwa_ssr.upstream.icmBaseURL }}"
        {{- if .Values.upstream.cdnPrefixURL }}
          - name: CDN_PREFIX_URL
            value: "{{ .Values.pwa_ssr.upstream.cdnPrefixURL }}"
        {{- end }}
        {{- range $key, $obj := .Values.pwa_ssr.extraEnvVars }}
          - name: {{ $obj.name }}
            value: {{ $obj.value | quote }}
        {{- end }}
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
          livenessProbe:
            {{- if empty .Values.pwa_ssr.livenessProbe }}
            exec:
              command:
                - node
                - /dist/livenessprobe.js
            initialDelaySeconds: 10
            periodSeconds: 5
            {{- else }}
              {{- with .Values.pwa_ssr.livenessProbe }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
          readinessProbe:
            {{- if empty .Values.pwa_ssr.readinessProbe }}
            exec:
              command:
                - node
                - /dist/readinessprobe.js
            initialDelaySeconds: 10
            periodSeconds: 5
            {{- else }}
              {{- with .Values.pwa_ssr.readinessProbe }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.pwa_ssr.resources | nindent 12 }}
      {{- with .Values.pwa_ssr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pwa_ssr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pwa_ssr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
