apiVersion: v1
kind: Service
metadata:
  name: {{ include "intershop-pwa.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "intershop-pwa.name" . }}
    helm.sh/chart: {{ include "intershop-pwa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.pwa_ssr.service.type }}
  ports:
    - port: {{ .Values.pwa_ssr.service.port }}
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "intershop-pwa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
